const seedRecipes=[
{id:1,title:"Macarrão cremoso",category:"Jantar",emoji:"🍝",time:"25 min",author:"Sabor & Panela",authorEmail:"official",description:"Macarrão cremoso, rápido e perfeito para um jantar simples.",ingredients:["250 g de macarrão","1 colher de manteiga","1/2 cebola picada","1 caixa de creme de leite","50 g de queijo ralado","Sal e pimenta a gosto"],steps:["Cozinhe o macarrão e reserve um pouco da água.","Refogue a cebola na manteiga.","Adicione creme de leite, queijo e temperos em fogo baixo.","Junte o macarrão e um pouco da água reservada.","Misture até ficar cremoso e sirva."]},
{id:2,title:"Frango grelhado",category:"Almoço",emoji:"🍗",time:"30 min",author:"Sabor & Panela",authorEmail:"official",description:"Frango dourado para acompanhar arroz, salada ou legumes.",ingredients:["2 filés de peito de frango","1 dente de alho","1 colher de azeite","Suco de 1/2 limão","Sal, páprica e pimenta"],steps:["Tempere o frango.","Aqueça a frigideira com azeite.","Grelhe dos dois lados.","Certifique-se de que esteja completamente cozido.","Sirva com os acompanhamentos."]},
{id:3,title:"Brigadeiro",category:"Sobremesa",emoji:"🍫",time:"20 min",author:"Sabor & Panela",authorEmail:"official",description:"Clássico brigadeiro para festas ou para adoçar o dia.",ingredients:["1 lata de leite condensado","1 colher de manteiga","3 colheres de chocolate em pó","Granulado"],steps:["Misture os ingredientes na panela.","Cozinhe em fogo baixo mexendo sempre.","Quando engrossar, desligue.","Espere esfriar.","Enrole e passe no granulado."]},
{id:4,title:"Panqueca de banana",category:"Café da manhã",emoji:"🥞",time:"15 min",author:"Sabor & Panela",authorEmail:"official",description:"Panquecas rápidas e deliciosas para começar o dia.",ingredients:["1 banana madura","1 ovo","3 colheres de aveia","Canela"],steps:["Amasse a banana.","Misture todos os ingredientes.","Aqueça uma frigideira levemente untada.","Coloque pequenas porções.","Doure os dois lados."]},
{id:5,title:"Sanduíche especial",category:"Lanche",emoji:"🥪",time:"10 min",author:"Sabor & Panela",authorEmail:"official",description:"Lanche rápido para qualquer hora do dia.",ingredients:["2 fatias de pão","Queijo","Presunto ou frango desfiado","Tomate","Alface","Molho"],steps:["Passe o molho no pão.","Monte os ingredientes.","Feche o sanduíche.","Aqueça se quiser.","Sirva."]},
{id:6,title:"Arroz de forno",category:"Almoço",emoji:"🍚",time:"40 min",author:"Sabor & Panela",authorEmail:"official",description:"Uma ótima forma de transformar arroz pronto em uma refeição.",ingredients:["3 xícaras de arroz cozido","1 xícara de frango","Milho","Ervilha","200 g de queijo","Molho de tomate"],steps:["Misture os ingredientes.","Coloque em uma travessa.","Cubra com queijo.","Leve ao forno até gratinar.","Sirva com cuidado."]}
];
const $=s=>document.querySelector(s),$$=s=>document.querySelectorAll(s);
const get=(k,d)=>JSON.parse(localStorage.getItem(k)||JSON.stringify(d));
const put=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
let recipes=get("sp_recipes",seedRecipes), current=null,rating=0,sortHigh=false;
const currentUser=()=>get("sp_session",null), users=()=>get("sp_users",[]);
const favs=()=>get("sp_favs",{}), reviews=()=>get("sp_reviews",{}), isAdmin=()=>currentUser()?.email==="admin@saborpanela.local";
function toast(t){let x=$("#toast");x.textContent=t;x.classList.add("show");setTimeout(()=>x.classList.remove("show"),2400)}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}
function avg(id){let a=reviews()[id]||[];return a.length?a.reduce((s,x)=>s+x.rating,0)/a.length:0}
function stars(n){return [1,2,3,4,5].map(i=>i<=Math.round(n)?"★":"☆").join("")}
function openModal(id){current=recipes.find(r=>r.id===id);if(!current)return;rating=0;$("#modalCover").textContent=current.emoji;$("#modalCat").textContent=current.category;$("#modalTitle").textContent=current.title;$("#modalAuthor").textContent=`👨‍🍳 por ${current.author}`;$("#modalDesc").textContent=current.description;$("#modalStars").textContent=stars(avg(id));$("#modalRating").textContent=avg(id).toFixed(1);$("#modalCount").textContent=`(${(reviews()[id]||[]).length} avaliações)`;$("#modalTime").textContent="⏱ "+current.time;$("#ingredients").innerHTML=current.ingredients.map(x=>`<li>${esc(x)}</li>`).join("");$("#steps").innerHTML=current.steps.map(x=>`<li>${esc(x)}</li>`).join("");updateFavButton();drawPicker();drawReviews();$("#recipeModal").classList.remove("hidden")}
function updateFavButton(){let f=favs()[currentUser().email]||[];$("#modalFav").textContent=f.includes(current.id)?"❤️ Remover favorito":"♡ Favoritar"}
function card(r){let f=favs()[currentUser().email]||[];return `<article class="recipe-card"><div class="cover">${r.emoji}<span class="tag cat">${esc(r.category)}</span><button class="heart" data-fav="${r.id}">${f.includes(r.id)?"❤️":"♡"}</button></div><div class="card-body"><h3>${esc(r.title)}</h3><p>${esc(r.description)}</p><div class="meta"><span>⏱ ${esc(r.time)}</span><span>⭐ ${avg(r.id).toFixed(1)}</span><span>👨‍🍳 ${esc(r.author)}</span></div><button class="view-btn" data-open="${r.id}">Ver receita completa</button></div></article>`}
function bindCards(){$$("[data-open]").forEach(b=>b.onclick=()=>openModal(+b.dataset.open));$$("[data-fav]").forEach(b=>b.onclick=()=>toggleFav(+b.dataset.fav))}
function toggleFav(id){let f=favs(),email=currentUser().email;f[email]=f[email]||[];f[email]=f[email].includes(id)?f[email].filter(x=>x!==id):[...f[email],id];put("sp_favs",f);toast(f[email].includes(id)?"Adicionada aos favoritos ❤️":"Removida dos favoritos");renderAll();if(current?.id===id)updateFavButton()}
function renderFilters(){let cats=["Todas","Almoço","Jantar","Sobremesa","Lanche","Café da manhã"];$("#filters").innerHTML=cats.map(c=>`<button class="filter ${c==="Todas"?"active":""}" data-cat="${c}">${c}</button>`).join("");$$("[data-cat]").forEach(b=>b.onclick=()=>{$$(".filter").forEach(x=>x.classList.remove("active"));b.classList.add("active");renderRecipes()})}
function renderRecipes(){let q=$("#search").value.toLowerCase(),cat=$(".filter.active")?.dataset.cat||"Todas";let a=recipes.filter(r=>(cat==="Todas"||r.category===cat)&&(r.title+" "+r.description+" "+r.category+" "+r.ingredients.join(" ")).toLowerCase().includes(q));$("#recipeGrid").innerHTML=a.map(card).join("");$("#empty").classList.toggle("hidden",a.length>0);bindCards()}
function renderCommunity(){let a=[...recipes].filter(r=>r.authorEmail!=="official");if(sortHigh)a.sort((x,y)=>avg(y.id)-avg(x.id));$("#communityGrid").innerHTML=a.length?a.map(card).join(""):`<div class="empty">Ainda não há receitas publicadas pela comunidade. Seja o primeiro! 👨‍🍳</div>`;bindCards()}
function renderFavorites(){let f=favs()[currentUser().email]||[],a=recipes.filter(r=>f.includes(r.id));$("#favoriteGrid").innerHTML=a.map(card).join("");$("#favoriteEmpty").classList.toggle("hidden",a.length>0);bindCards()}
function renderStats(){let rev=Object.values(reviews()).flat();$("#statRecipes").textContent=recipes.length;$("#statUsers").textContent=users().length;$("#pRecipes").textContent=recipes.filter(r=>r.authorEmail===currentUser().email).length;$("#pFavs").textContent=(favs()[currentUser().email]||[]).length;$("#pReviews").textContent=rev.filter(x=>x.email===currentUser().email).length}
function renderAll(){renderFilters();renderRecipes();renderCommunity();renderFavorites();renderStats()}
function drawPicker(){$("#starPicker").innerHTML=[1,2,3,4,5].map(i=>`<button data-star="${i}" class="${i<=rating?"selected":""}">★</button>`).join("");$$("[data-star]").forEach(b=>b.onclick=()=>{rating=+b.dataset.star;drawPicker()})}
function drawReviews(){let a=reviews()[current.id]||[];$("#reviews").innerHTML=a.length?a.map(x=>`<div class="review-item"><div class="review-head"><b>${esc(x.name)}</b><span class="stars">${stars(x.rating)} • ${esc(x.date)}</span></div><p>${esc(x.text||"Sem comentário.")}</p></div>`).join(""):"<p class='empty'>Ainda não há avaliações. Seja o primeiro!</p>"}
function closeModals(){ $$(".modal").forEach(m=>m.classList.add("hidden")) }
$$("[data-close]").forEach(x=>x.onclick=closeModals);
$("#modalFav").onclick=()=>toggleFav(current.id);
$("#reviewBtn").onclick=()=>{if(!rating)return toast("Escolha uma nota de 1 a 5 estrelas.");let all=reviews();all[current.id]=all[current.id]||[];all[current.id].unshift({name:currentUser().name,email:currentUser().email,rating,text:$("#reviewText").value.trim(),date:new Date().toLocaleDateString("pt-BR")});put("sp_reviews",all);$("#reviewText").value="";rating=0;drawPicker();drawReviews();renderAll();$("#modalStars").textContent=stars(avg(current.id));$("#modalRating").textContent=avg(current.id).toFixed(1);$("#modalCount").textContent=`(${all[current.id].length} avaliações)`;toast("Avaliação publicada ⭐")};
async function share(){let text=`Confira "${current.title}" no Sabor & Panela!`;try{if(navigator.share)await navigator.share({title:current.title,text,url:location.href+"#recipe-"+current.id});else{await navigator.clipboard.writeText(text+" "+location.href);toast("Link copiado! 🔗")}}catch{}}
$("#shareBtn").onclick=share;
$("#copyBtn").onclick=async()=>{try{await navigator.clipboard.writeText(location.href+"#recipe-"+current.id);toast("Link copiado! 🔗")}catch{toast("Não foi possível copiar automaticamente.")}};
$("#search").oninput=renderRecipes;$("#sortBtn").onclick=()=>{sortHigh=!sortHigh;$("#sortBtn").textContent=sortHigh?"↕ Ordem padrão":"⭐ Mais avaliadas";renderCommunity()};
function openCreate(){$("#createModal").classList.remove("hidden")}
$("#newRecipeBtn").onclick=openCreate;$("#heroCreate").onclick=openCreate;
$("#recipeForm").onsubmit=e=>{e.preventDefault();let r={id:Date.now(),title:$("#rTitle").value.trim(),category:$("#rCategory").value,emoji:$("#rEmoji").value||"🍲",time:$("#rTime").value.trim(),author:currentUser().name,authorEmail:currentUser().email,description:$("#rDesc").value.trim(),ingredients:$("#rIngredients").value.split("\n").map(x=>x.trim()).filter(Boolean),steps:$("#rSteps").value.split("\n").map(x=>x.trim()).filter(Boolean)};recipes.push(r);put("sp_recipes",recipes);e.target.reset();$("#rEmoji").value="🍲";closeModals();renderAll();toast("Receita publicada com sucesso! 🚀");location.hash="community"};
$("#profileBtn").onclick=()=>{let u=currentUser();$("#bigAvatar").textContent=u.name[0].toUpperCase();$("#profileName").textContent=u.name;$("#profileEmail").textContent=u.email;let mine=recipes.filter(r=>r.authorEmail===u.email);$("#myRecipes").innerHTML=mine.length?mine.map(r=>`<div class="mini-item"><span>${r.emoji} ${esc(r.title)}</span><b>⭐ ${avg(r.id).toFixed(1)}</b></div>`).join(""):"<p class='empty'>Você ainda não publicou receitas.</p>";$("#profileModal").classList.remove("hidden")};
$("#themeBtn").onclick=()=>{document.body.classList.toggle("dark");let dark=document.body.classList.contains("dark");localStorage.setItem("sp_dark",dark);$("#themeBtn").textContent=dark?"☀️":"🌙"};
if(localStorage.getItem("sp_dark")==="true"){document.body.classList.add("dark");$("#themeBtn").textContent="☀️"}
$("#menuBtn").onclick=()=>$("#nav").classList.toggle("open");$$("nav a").forEach(a=>a.onclick=()=>$("#nav").classList.remove("open"));
$("#logoutBtn").onclick=()=>{localStorage.removeItem("sp_session");location.reload()};
$("#settingsBtn").onclick=()=>$("#settingsMenu").classList.toggle("hidden");
$("#settingsTheme").onclick=()=>{$("#themeBtn").click();$("#settingsMenu").classList.add("hidden")};
$("#settingsProfile").onclick=()=>{$("#profileBtn").click();$("#settingsMenu").classList.add("hidden")};
$("#settingsTop").onclick=()=>{window.scrollTo({top:0,behavior:"smooth"});$("#settingsMenu").classList.add("hidden")};
$("#settingsLogout").onclick=()=>{$("#logoutBtn").click()};
document.addEventListener("click",e=>{if(!e.target.closest(".settings-wrap"))$("#settingsMenu")?.classList.add("hidden")});

function admin(){if(!isAdmin())return toast("Área restrita.");$("#aRecipes").textContent=recipes.length;$("#aUsers").textContent=users().length;$("#aReviews").textContent=Object.values(reviews()).flat().length;$("#adminList").innerHTML=recipes.map(r=>`<div class="admin-item"><span>${r.emoji} ${esc(r.title)}<small> — ${esc(r.author)}</small></span><button class="logout" data-delete="${r.id}">Excluir</button></div>`).join("");$$("[data-delete]").forEach(b=>b.onclick=()=>{recipes=recipes.filter(r=>r.id!==+b.dataset.delete);put("sp_recipes",recipes);admin();renderAll();toast("Receita removida.")});$("#adminModal").classList.remove("hidden")}
document.addEventListener("keydown",e=>{if(e.key==="Escape")closeModals()});
function start(){let u=currentUser();if(!u){$("#authScreen").classList.remove("hidden");return}$("#authScreen").classList.add("hidden");$("#app").classList.remove("hidden");$("#userName").textContent=u.name;$("#avatarMini").textContent=u.name[0].toUpperCase();renderAll();if(isAdmin()){$("#profileBtn").addEventListener("contextmenu",e=>{e.preventDefault();admin()})}}
$$(".auth-tab").forEach(b=>b.onclick=()=>{$$(".auth-tab").forEach(x=>x.classList.remove("active"));b.classList.add("active");let login=b.dataset.auth==="login";$("#loginForm").classList.toggle("hidden",!login);$("#registerForm").classList.toggle("hidden",login)});
$("#registerForm").onsubmit=e=>{e.preventDefault();let name=$("#regName").value.trim(),email=$("#regEmail").value.trim().toLowerCase(),pass=$("#regPass").value;if(pass!==$("#regConfirm").value)return $("#regMsg").textContent="As senhas não coincidem.";let u=users();if(u.some(x=>x.email===email))return $("#regMsg").textContent="E-mail já cadastrado.";u.push({name,email,password:pass});put("sp_users",u);$("#regMsg").textContent="Conta criada! Agora entre.";$("#regMsg").style.color="#2d8a52";setTimeout(()=>{$('[data-auth="login"]').click();$("#loginEmail").value=email},600)};
$("#loginForm").onsubmit=e=>{e.preventDefault();let email=$("#loginEmail").value.trim().toLowerCase(),pass=$("#loginPassword").value,u=users().find(x=>x.email===email&&x.password===pass);if(email==="admin@saborpanela.local"&&pass==="admin123"){u={name:"Administrador",email,password:pass};if(!users().some(x=>x.email===email)){let a=users();a.push(u);put("sp_users",a)}}if(!u)return $("#loginMsg").textContent="E-mail ou senha incorretos.";put("sp_session",{name:u.name,email:u.email});location.reload()};
start();
